apiVersion: v1
kind: Secret
metadata:
  name: app-secret-db
  namespace: test
type: Opaque
stringData:
  APP_PASSWORD: "Password123!"

  #creation de secret TLS
  #kubectl create secret tls xxxxxxxxx --namespace dev --key private-key.txt --cert cetificate.crt 